# Generated by Django 4.1.4 on 2022-12-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenarchersguildapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshotcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='screenshotcategory',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='screenshotcategory',
            name='category',
            field=models.ManyToManyField(to='screenarchersguildapi.category'),
        ),
        migrations.AddField(
            model_name='screenshotcategory',
            name='screenshot',
            field=models.ManyToManyField(to='screenarchersguildapi.screenshot'),
        ),
    ]
