# Generated by Django 4.1.4 on 2022-12-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenarchersguildapi', '0002_rename_ismooded_screenshot_ismodded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='publishing_date',
            field=models.DateField(verbose_name='%Y-%m-%d'),
        ),
    ]
