# Generated by Django 4.1.4 on 2022-12-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenarchersguildapi', '0004_alter_guide_publishing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='publishing_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
