# Generated by Django 4.1.4 on 2022-12-16 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screenarchersguildapi', '0005_alter_guide_publishing_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='isModded',
        ),
    ]
